version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./:/workspaces/bpu:cached
      - ${HOME}/.ssh:/home/vscode/.ssh
    network_mode: service:db
    command: sleep infinity
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    # profiles:
    #   - db
    volumes: 
      - db:/var/lib/postgresql/data  
volumes:
  db:
    driver: local